// NOTE: should come from rest api

import { PaymentMethodsResponseObject } from '@adyen/adyen-web/dist/types/core/ProcessResponse/PaymentMethodsResponse/types';

export const sleep = <T>(response: T, timeout = 250): Promise<T> =>
  new Promise((res) => setTimeout(() => res(response), timeout));

export const paymentMethods: any = {
  groups: [{ name: 'Credit Card', types: ['visa', 'mc', 'amex'] }],
  oneClickPaymentMethods: [
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'VISA',
      type: 'visa',
      recurringDetailReference: '8416218707143533',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'Test', number: '0003' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'VISA',
      type: 'visa',
      recurringDetailReference: '8316218517651114',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'Test', number: '0001' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'VISA',
      type: 'visa',
      recurringDetailReference: '8416218515557171',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'Test', number: '0000' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'MasterCard',
      type: 'mc',
      recurringDetailReference: '8416195334926078',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'Test', number: '0009' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'MasterCard',
      type: 'mc',
      recurringDetailReference: '8316195326533503',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'test', number: '0008' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'MasterCard',
      type: 'mc',
      recurringDetailReference: '8316194449310329',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'test', number: '5454' } },
    },
    {
      details: [{ key: 'cardDetails.cvc', type: 'cvc' }],
      name: 'MasterCard',
      type: 'mc',
      recurringDetailReference: '8416194400061795',
      storedDetails: { card: { expiryMonth: '3', expiryYear: '2030', holderName: 'test', number: '4444' } },
    },
  ],
  paymentMethods: [
    {
      brands: ['visa', 'mc', 'amex'],
      details: [
        { key: 'encryptedCardNumber', type: 'cardToken' },
        { key: 'encryptedSecurityCode', type: 'cardToken' },
        { key: 'encryptedExpiryMonth', type: 'cardToken' },
        { key: 'encryptedExpiryYear', type: 'cardToken' },
        { key: 'holderName', optional: true, type: 'text' },
      ],
      name: 'Credit Card',
      type: 'scheme',
    },
    {
      details: [{ key: 'applepay.token', type: 'applePayToken' }],
      name: 'Apple Pay',
      supportsRecurring: true,
      type: 'applepay',
    },
    {
      details: [{ key: 'paywithgoogle.token', type: 'payWithGoogleToken' }],
      name: 'Google Pay',
      supportsRecurring: true,
      type: 'paywithgoogle',
    },
  ],
  storedPaymentMethods: [
    {
      brand: 'visa',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'Test',
      id: '8416218707143533',
      lastFour: '0003',
      name: 'VISA',
      supportedShopperInteractions: ['Ecommerce', 'ContAuth'],
      type: 'scheme',
    },
    {
      brand: 'visa',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'Test',
      id: '8316218517651114',
      lastFour: '0001',
      name: 'VISA',
      supportedShopperInteractions: ['ContAuth', 'Ecommerce'],
      type: 'scheme',
    },
    {
      brand: 'visa',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'Test',
      id: '8416218515557171',
      lastFour: '0000',
      name: 'VISA',
      supportedShopperInteractions: ['ContAuth', 'Ecommerce'],
      type: 'scheme',
    },
    {
      brand: 'mc',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'Test',
      id: '8416195334926078',
      lastFour: '0009',
      name: 'MasterCard',
      supportedShopperInteractions: ['ContAuth', 'Ecommerce'],
      type: 'scheme',
    },
    {
      brand: 'mc',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'test',
      id: '8316195326533503',
      lastFour: '0008',
      name: 'MasterCard',
      supportedShopperInteractions: ['Ecommerce', 'ContAuth'],
      type: 'scheme',
    },
    {
      brand: 'mc',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'test',
      id: '8316194449310329',
      lastFour: '5454',
      name: 'MasterCard',
      supportedShopperInteractions: ['ContAuth', 'Ecommerce'],
      type: 'scheme',
    },
    {
      brand: 'mc',
      expiryMonth: '03',
      expiryYear: '2030',
      holderName: 'test',
      id: '8416194400061795',
      lastFour: '4444',
      name: 'MasterCard',
      supportedShopperInteractions: ['ContAuth', 'Ecommerce'],
      type: 'scheme',
    },
  ],
};

export const getPaymentMethods = () => sleep<PaymentMethodsResponseObject>(paymentMethods);

export const getClientConfig = () =>
  sleep({ environment: 'TEST', clientKey: process.env.REACT_APP_ADYEN_CLIENT_KEY });

export const getPaymentSources = () =>
  sleep([
    {
      id: 'pm_16CI0lSVnBUWvOaN',
      customerId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4',
      type: 'card',
      status: 'valid',
      isPrimaryPaymentSource: true,
      referenceId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4/8416195334926078',
      createdAt: 1619533493000,
      card: {
        firstName: 'Test',
        last4: '0009',
        brand: 'mastercard',
        fundingType: 'notKnown',
        expiryMonth: 3,
        expiryYear: 2030,
        billingAddressLine1: 'wndqoi',
        billingAddressLine2: 'onqdwuoidn',
        billingAddressCity: 'onqwduiq',
        billingAddressPostalCode: 'bn114ne',
      },
      deleted: false,
    },
    {
      id: 'pm_16CI0lSVn7yS9MNB',
      customerId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4',
      type: 'card',
      status: 'valid',
      isPrimaryPaymentSource: false,
      referenceId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4/8316195326533503',
      createdAt: 1619532655000,
      card: {
        firstName: 'test',
        last4: '0008',
        brand: 'mastercard',
        fundingType: 'notKnown',
        expiryMonth: 3,
        expiryYear: 2030,
        billingAddressLine1: 'nnasdu',
        billingAddressLine2: 'doiqwn',
        billingAddressCity: 'odqiwn',
        billingAddressPostalCode: 'bn114ne',
      },
      deleted: false,
    },
    {
      id: 'pm_16BjhDSVhBtkhFv4',
      customerId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4',
      type: 'card',
      status: 'valid',
      isPrimaryPaymentSource: false,
      referenceId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4/8316194449310329',
      createdAt: 1619444932000,
      card: {
        firstName: 'test',
        last4: '5454',
        brand: 'mastercard',
        fundingType: 'notKnown',
        expiryMonth: 3,
        expiryYear: 2030,
        billingAddressLine1: '24 Mill House Gardens',
        billingAddressLine2: 'Mill Road',
        billingAddressCity: 'Worthing',
        billingAddressPostalCode: 'BN11 4NE',
      },
      deleted: false,
    },
    {
      id: 'pm_AzZlzXSVgrEfAAVG',
      customerId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4',
      type: 'card',
      status: 'valid',
      isPrimaryPaymentSource: false,
      referenceId: 'be797d75-912f-6c4b-1ae1-a37a2b1492a4/8416194400061795',
      createdAt: 1619440008000,
      card: {
        firstName: 'test',
        last4: '4444',
        brand: 'mastercard',
        fundingType: 'notKnown',
        expiryMonth: 3,
        expiryYear: 2030,
        billingAddressLine1: '24 Mill House Gardens',
        billingAddressLine2: 'Mill Road',
        billingAddressCity: 'Worthing',
        billingAddressPostalCode: 'BN11 4NE',
      },
      deleted: false,
    },
  ]);
